const { SCOPES } = require("@modules/permissions");

const ROLE_NAMES = {
    BANNED: "Banned",
    GUEST: "Guest",
    STUDENT: "Student",
    MOD: "Mod",
    TEACHER: "Teacher",
    MANAGER: "Manager",
};

const DEFAULT_BANNED_SCOPES = {
    global: [],
    class: [],
};

const DEFAULT_GUEST_SCOPES = {
    global: [],
    class: [SCOPES.CLASS.POLL.READ, SCOPES.CLASS.DIGIPOGS.AWARD, SCOPES.CLASS.LINKS.READ],
};

const DEFAULT_STUDENT_SCOPES = {
    global: [SCOPES.GLOBAL.POOLS.MANAGE],
    class: [
        SCOPES.CLASS.POLL.READ,
        SCOPES.CLASS.POLL.VOTE,
        SCOPES.CLASS.BREAK.REQUEST,
        SCOPES.CLASS.HELP.REQUEST,
        SCOPES.CLASS.DIGIPOGS.AWARD,

        ...DEFAULT_GUEST_SCOPES.class,
    ],
};

const DEFAULT_MOD_SCOPES = {
    global: [...DEFAULT_STUDENT_SCOPES.global],
    class: [
        SCOPES.CLASS.POLL.CREATE,
        SCOPES.CLASS.POLL.END,
        SCOPES.CLASS.POLL.DELETE,
        SCOPES.CLASS.POLL.SHARE,

        SCOPES.CLASS.BREAK.APPROVE,
        SCOPES.CLASS.HELP.APPROVE,

        SCOPES.CLASS.AUXILIARY.CONTROL,
        SCOPES.CLASS.GAMES.ACCESS,
        SCOPES.CLASS.TAGS.MANAGE,
        SCOPES.CLASS.LINKS.MANAGE,

        ...DEFAULT_STUDENT_SCOPES.class,
    ],
};

const DEFAULT_TEACHER_SCOPES = {
    global: [SCOPES.GLOBAL.CLASS.CREATE, SCOPES.GLOBAL.CLASS.DELETE, SCOPES.GLOBAL.DIGIPOGS.AWARD],
    class: [
        SCOPES.CLASS.STUDENTS.READ,
        SCOPES.CLASS.STUDENTS.KICK,
        SCOPES.CLASS.STUDENTS.BAN,
        SCOPES.CLASS.STUDENTS.PERM_CHANGE,

        SCOPES.CLASS.SESSION.START,
        SCOPES.CLASS.SESSION.END,
        SCOPES.CLASS.SESSION.RENAME,
        SCOPES.CLASS.SESSION.SETTINGS,
        SCOPES.CLASS.SESSION.REGENERATE_CODE,

        SCOPES.CLASS.TIMER.CONTROL,

        ...DEFAULT_MOD_SCOPES.class,
    ],
};

const DEFAULT_MANAGER_SCOPES = {
    global: [SCOPES.GLOBAL.SYSTEM.ADMIN, SCOPES.GLOBAL.USERS.MANAGE, ...DEFAULT_TEACHER_SCOPES.global],
    class: [...DEFAULT_TEACHER_SCOPES.class],
};

// Maps role names to their default scope sets
const ROLES = {
    [ROLE_NAMES.BANNED]: DEFAULT_BANNED_SCOPES,
    [ROLE_NAMES.GUEST]: DEFAULT_GUEST_SCOPES,
    [ROLE_NAMES.STUDENT]: DEFAULT_STUDENT_SCOPES,
    [ROLE_NAMES.MOD]: DEFAULT_MOD_SCOPES,
    [ROLE_NAMES.TEACHER]: DEFAULT_TEACHER_SCOPES,
    [ROLE_NAMES.MANAGER]: DEFAULT_MANAGER_SCOPES,
};

// Maps legacy numeric permission levels to role names
const LEVEL_TO_ROLE = {
    0: ROLE_NAMES.BANNED,
    1: ROLE_NAMES.GUEST,
    2: ROLE_NAMES.STUDENT,
    3: ROLE_NAMES.MOD,
    4: ROLE_NAMES.TEACHER,
    5: ROLE_NAMES.MANAGER,
};

module.exports = {
    ROLE_NAMES,
    ROLES,
    LEVEL_TO_ROLE,
};
