const { SCOPES } = require("@modules/permissions");

const DEFAULT_STUDENT_PERMISSIONS = {
    global: [],
    class: [
        SCOPES.CLASS.POLL.READ,
        SCOPES.CLASS.POLL.VOTE,
        SCOPES.CLASS.BREAK.REQUEST,
        SCOPES.CLASS.HELP.REQUEST
    ],
}

const DEFAULT_TEACHER_PERMISSIONS = {
    global: [
        SCOPES.GLOBAL.CLASS.CREATE,
        SCOPES.GLOBAL.CLASS.DELETE,
        SCOPES.GLOBAL.DIGIPOGS.AWARD,
    ],
    class: [
        SCOPES.CLASS.POLL.CREATE,
        SCOPES.CLASS.POLL.DELETE,
        SCOPES.CLASS.POLL.END,

        SCOPES.CLASS.STUDENTS.READ,
        SCOPES.CLASS.STUDENTS.KICK,
        SCOPES.CLASS.STUDENTS.BAN,
        SCOPES.CLASS.STUDENTS.PERM_CHANGE,

        SCOPES.CLASS.SESSION.START,
        SCOPES.CLASS.SESSION.END,
        SCOPES.CLASS.SESSION.RENAME,
        SCOPES.CLASS.SESSION.SETTINGS,
        SCOPES.CLASS.SESSION.REGENERATE_CODE,

        SCOPES.CLASS.BREAK.APPROVE,
        SCOPES.CLASS.HELP.APPROVE,

        SCOPES.CLASS.TIMER.CONTROL,
        SCOPES.CLASS.AUXILIARY.CONTROL,
        SCOPES.CLASS.DIGIPOGS.AWARD,

        ...DEFAULT_STUDENT_PERMISSIONS.class,
    ]
};

const DEFAULT_MANAGER_PERMISSIONS = {
    global: [
        SCOPES.GLOBAL.SYSTEM.ADMIN,
        SCOPES.GLOBAL.USERS.MANAGE,
        ...DEFAULT_TEACHER_PERMISSIONS.global,
    ],
    class: []
};

const ROLES = {
    MANAGER: DEFAULT_MANAGER_PERMISSIONS,
    TEACHER: DEFAULT_TEACHER_PERMISSIONS,
    STUDENT: DEFAULT_STUDENT_PERMISSIONS
};

module.exports = {
    ROLES
}